CREATE OR REPLACE FUNCTION vrr.InterpolatePVTCompletionTest(
    pressure FLOAT,
    completion VARCHAR(32),
    vrr_date DATE
)
RETURNS TABLE (
    PRESSURE FLOAT,
    OIL_FORMATION_VOLUME_FACTOR FLOAT,
    GAS_FORMATION_VOLUME_FACTOR FLOAT,
    WATER_FORMATION_VOLUME_FACTOR FLOAT,
    SOLUTION_GAS_OIL_RATIO FLOAT,
    VOLATIZED_OIL_GAS_RATIO FLOAT,
    VISCOSITY_OIL FLOAT,
    VISCOSITY_WATER FLOAT,
    VISCOSITY_GAS FLOAT,
    INJECTED_GAS_FORMATION_VOLUME_FACTOR FLOAT,
    INJECTED_WATER_FORMATION_VOLUME_FACTOR FLOAT
)
AS
$$
BEGIN
  -- Create temporary tables for future implementation
  CREATE TEMPORARY TABLE IF NOT EXISTS ExactMatch (
      PRESSURE FLOAT,
      OIL_FORMATION_VOLUME_FACTOR FLOAT,
      GAS_FORMATION_VOLUME_FACTOR FLOAT,
      WATER_FORMATION_VOLUME_FACTOR FLOAT,
      SOLUTION_GAS_OIL_RATIO FLOAT,
      VOLATIZED_OIL_GAS_RATIO FLOAT,
      VISCOSITY_OIL FLOAT,
      VISCOSITY_WATER FLOAT,
      VISCOSITY_GAS FLOAT,
      INJECTED_GAS_FORMATION_VOLUME_FACTOR FLOAT,
      INJECTED_WATER_FORMATION_VOLUME_FACTOR FLOAT
  );

  CREATE TEMPORARY TABLE IF NOT EXISTS lowerbound (
      PRESSURE FLOAT,
      OIL_FORMATION_VOLUME_FACTOR FLOAT,
      GAS_FORMATION_VOLUME_FACTOR FLOAT,
      WATER_FORMATION_VOLUME_FACTOR FLOAT,
      SOLUTION_GAS_OIL_RATIO FLOAT,
      VOLATIZED_OIL_GAS_RATIO FLOAT,
      VISCOSITY_OIL FLOAT,
      VISCOSITY_WATER FLOAT,
      VISCOSITY_GAS FLOAT,
      INJECTED_GAS_FORMATION_VOLUME_FACTOR FLOAT,
      INJECTED_WATER_FORMATION_VOLUME_FACTOR FLOAT
  );

  CREATE TEMPORARY TABLE IF NOT EXISTS upperbound (
      PRESSURE FLOAT,
      OIL_FORMATION_VOLUME_FACTOR FLOAT,
      GAS_FORMATION_VOLUME_FACTOR FLOAT,
      WATER_FORMATION_VOLUME_FACTOR FLOAT,
      SOLUTION_GAS_OIL_RATIO FLOAT,
      VOLATIZED_OIL_GAS_RATIO FLOAT,
      VISCOSITY_OIL FLOAT,
      VISCOSITY_WATER FLOAT,
      VISCOSITY_GAS FLOAT,
      INJECTED_GAS_FORMATION_VOLUME_FACTOR FLOAT,
      INJECTED_WATER_FORMATION_VOLUME_FACTOR FLOAT
  );

  CREATE TEMPORARY TABLE IF NOT EXISTS secondBOUND (
      PRESSURE FLOAT,
      OIL_FORMATION_VOLUME_FACTOR FLOAT,
      GAS_FORMATION_VOLUME_FACTOR FLOAT,
      WATER_FORMATION_VOLUME_FACTOR FLOAT,
      SOLUTION_GAS_OIL_RATIO FLOAT,
      VOLATIZED_OIL_GAS_RATIO FLOAT,
      VISCOSITY_OIL FLOAT,
      VISCOSITY_WATER FLOAT,
      VISCOSITY_GAS FLOAT,
      INJECTED_GAS_FORMATION_VOLUME_FACTOR FLOAT,
      INJECTED_WATER_FORMATION_VOLUME_FACTOR FLOAT
  );

  CREATE TEMPORARY TABLE IF NOT EXISTS interpolatedValues (
      PRESSURE FLOAT,
      OIL_FORMATION_VOLUME_FACTOR FLOAT,
      GAS_FORMATION_VOLUME_FACTOR FLOAT,
      WATER_FORMATION_VOLUME_FACTOR FLOAT,
      SOLUTION_GAS_OIL_RATIO FLOAT,
      VOLATIZED_OIL_GAS_RATIO FLOAT,
      VISCOSITY_OIL FLOAT,
      VISCOSITY_WATER FLOAT,
      VISCOSITY_GAS FLOAT,
      INJECTED_GAS_FORMATION_VOLUME_FACTOR FLOAT,
      INJECTED_WATER_FORMATION_VOLUME_FACTOR FLOAT
  );

  CREATE TEMPORARY TABLE IF NOT EXISTS PVTwithEndDate (
      ID_COMPLETION VARCHAR(32),
      TEST_DATE DATE,
      PRESSURE FLOAT,
      OIL_FORMATION_VOLUME_FACTOR FLOAT,
      GAS_FORMATION_VOLUME_FACTOR FLOAT,
      WATER_FORMATION_VOLUME_FACTOR FLOAT,
      SOLUTION_GAS_OIL_RATIO FLOAT,
      VOLATIZED_OIL_GAS_RATIO FLOAT,
      VISCOSITY_OIL FLOAT,
      VISCOSITY_WATER FLOAT,
      VISCOSITY_GAS FLOAT,
      INJECTED_GAS_FORMATION_VOLUME_FACTOR FLOAT,
      INJECTED_WATER_FORMATION_VOLUME_FACTOR FLOAT,
      END_DATE DATE
  );

  -- Return a dummy result with the input pressure and NULL for all other values
  RETURN TABLE(
    SELECT 
      pressure AS PRESSURE,
      NULL AS OIL_FORMATION_VOLUME_FACTOR,
      NULL AS GAS_FORMATION_VOLUME_FACTOR,
      NULL AS WATER_FORMATION_VOLUME_FACTOR,
      NULL AS SOLUTION_GAS_OIL_RATIO,
      NULL AS VOLATIZED_OIL_GAS_RATIO,
      NULL AS VISCOSITY_OIL,
      NULL AS VISCOSITY_WATER,
      NULL AS VISCOSITY_GAS,
      NULL AS INJECTED_GAS_FORMATION_VOLUME_FACTOR,
      NULL AS INJECTED_WATER_FORMATION_VOLUME_FACTOR
  );
END
$$;
