-- Create view for InterpolatePVTCompletionTest
CREATE OR REPLACE VIEW RMDE_SAM_ACC.INTERPOLATE_PVT_COMPLETION_TEST_VIEW
AS
WITH PVTwithEndDate AS (
    SELECT
        ID_COMPLETION,
        TEST_DATE,
        PRESSURE,
        OIL_FORMATION_VOLUME_FACTOR,
        GAS_FORMATION_VOLUME_FACTOR,
        WATER_FORMATION_VOLUME_FACTOR,
        SOLUTION_GAS_OIL_RATIO,
        VOLATIZED_OIL_GAS_RATIO,
        VISCOSITY_OIL,
        VISCOSITY_WATER,
        VISCOSITY_GAS,
        INJECTED_GAS_FORMATION_VOLUME_FACTOR,
        INJECTED_WATER_FORMATION_VOLUME_FACTOR,
        COALESCE(
            (SELECT MIN(TEST_DATE)
             FROM RMDE_SAM_ACC.COMPLETION_PVT_CHARACTERISTICS cpvt
             WHERE cpvt.TEST_DATE > cpc.TEST_DATE
               AND cpvt.ID_COMPLETION = cpc.ID_COMPLETION),
            '9999-12-31'::DATE
        ) AS END_DATE,
        completion AS INPUT_COMPLETION,
        pressure AS INPUT_PRESSURE,
        vrr_date AS INPUT_VRR_DATE
    FROM RMDE_SAM_ACC.COMPLETION_PVT_CHARACTERISTICS cpc
    CROSS JOIN (SELECT DISTINCT ID_COMPLETION AS completion, PRESSURE AS pressure, DATE AS vrr_date 
                FROM RMDE_SAM_ACC.PATTERN_PRESSURE) inputs
    WHERE ID_COMPLETION = completion
      AND TEST_DATE <= LAST_DAY(vrr_date)
),
ExactMatch AS (
    SELECT
        INPUT_PRESSURE AS PRESSURE,
        OIL_FORMATION_VOLUME_FACTOR,
        GAS_FORMATION_VOLUME_FACTOR,
        WATER_FORMATION_VOLUME_FACTOR,
        SOLUTION_GAS_OIL_RATIO,
        VOLATIZED_OIL_GAS_RATIO,
        VISCOSITY_OIL,
        VISCOSITY_WATER,
        VISCOSITY_GAS,
        INJECTED_GAS_FORMATION_VOLUME_FACTOR,
        INJECTED_WATER_FORMATION_VOLUME_FACTOR,
        INPUT_COMPLETION AS completion,
        INPUT_VRR_DATE AS vrr_date
    FROM PVTwithEndDate
    WHERE TEST_DATE = (
        SELECT MAX(TEST_DATE)
        FROM PVTwithEndDate p
        WHERE p.PRESSURE = INPUT_PRESSURE
          AND p.ID_COMPLETION = INPUT_COMPLETION
          AND p.TEST_DATE <= LAST_DAY(INPUT_VRR_DATE)
    )
      AND PRESSURE = INPUT_PRESSURE
    QUALIFY ROW_NUMBER() OVER (PARTITION BY INPUT_COMPLETION, INPUT_PRESSURE, INPUT_VRR_DATE ORDER BY TEST_DATE DESC) = 1
),
LowerBound AS (
    SELECT
        PRESSURE,
        OIL_FORMATION_VOLUME_FACTOR,
        GAS_FORMATION_VOLUME_FACTOR,
        WATER_FORMATION_VOLUME_FACTOR,
        SOLUTION_GAS_OIL_RATIO,
        VOLATIZED_OIL_GAS_RATIO,
        VISCOSITY_OIL,
        VISCOSITY_WATER,
        VISCOSITY_GAS,
        INJECTED_GAS_FORMATION_VOLUME_FACTOR,
        INJECTED_WATER_FORMATION_VOLUME_FACTOR,
        INPUT_COMPLETION AS completion,
        INPUT_VRR_DATE AS vrr_date
    FROM PVTwithEndDate
    WHERE PRESSURE < INPUT_PRESSURE
      AND ID_COMPLETION = INPUT_COMPLETION
      AND TEST_DATE <= LAST_DAY(INPUT_VRR_DATE)
    QUALIFY ROW_NUMBER() OVER (PARTITION BY INPUT_COMPLETION, INPUT_VRR_DATE ORDER BY PRESSURE DESC, TEST_DATE DESC) = 1
),
UpperBound AS (
    SELECT
        PRESSURE,
        OIL_FORMATION_VOLUME_FACTOR,
        GAS_FORMATION_VOLUME_FACTOR,
        WATER_FORMATION_VOLUME_FACTOR,
        SOLUTION_GAS_OIL_RATIO,
        VOLATIZED_OIL_GAS_RATIO,
        VISCOSITY_OIL,
        VISCOSITY_WATER,
        VISCOSITY_GAS,
        INJECTED_GAS_FORMATION_VOLUME_FACTOR,
        INJECTED_WATER_FORMATION_VOLUME_FACTOR,
        INPUT_COMPLETION AS completion,
        INPUT_VRR_DATE AS vrr_date
    FROM PVTwithEndDate
    WHERE PRESSURE > INPUT_PRESSURE
      AND ID_COMPLETION = INPUT_COMPLETION
      AND TEST_DATE <= LAST_DAY(INPUT_VRR_DATE)
    QUALIFY ROW_NUMBER() OVER (PARTITION BY INPUT_COMPLETION, INPUT_VRR_DATE ORDER BY PRESSURE ASC, TEST_DATE DESC) = 1
),
SecondBound AS (
    SELECT
        PRESSURE,
        OIL_FORMATION_VOLUME_FACTOR,
        GAS_FORMATION_VOLUME_FACTOR,
        WATER_FORMATION_VOLUME_FACTOR,
        SOLUTION_GAS_OIL_RATIO,
        VOLATIZED_OIL_GAS_RATIO,
        VISCOSITY_OIL,
        VISCOSITY_WATER,
        VISCOSITY_GAS,
        INJECTED_GAS_FORMATION_VOLUME_FACTOR,
        INJECTED_WATER_FORMATION_VOLUME_FACTOR,
        INPUT_COMPLETION AS completion,
        INPUT_VRR_DATE AS vrr_date
    FROM PVTwithEndDate pvt
    WHERE pvt.PRESSURE = (
        SELECT MIN(pressure)
        FROM PVTwithEndDate p
        WHERE p.PRESSURE > (SELECT PRESSURE FROM UpperBound WHERE UpperBound.completion = pvt.INPUT_COMPLETION AND UpperBound.vrr_date = pvt.INPUT_VRR_DATE)
          AND p.ID_COMPLETION = INPUT_COMPLETION
          AND p.TEST_DATE <= LAST_DAY(INPUT_VRR_DATE)
    )
      AND pvt.ID_COMPLETION = INPUT_COMPLETION
      AND pvt.TEST_DATE <= LAST_DAY(INPUT_VRR_DATE)
    QUALIFY ROW_NUMBER() OVER (PARTITION BY INPUT_COMPLETION, INPUT_VRR_DATE ORDER BY TEST_DATE DESC) = 1
),
InterpolatedValues AS (
    -- Exact match
    SELECT
        PRESSURE,
        OIL_FORMATION_VOLUME_FACTOR,
        GAS_FORMATION_VOLUME_FACTOR,
        WATER_FORMATION_VOLUME_FACTOR,
        SOLUTION_GAS_OIL_RATIO,
        VOLATIZED_OIL_GAS_RATIO,
        VISCOSITY_OIL,
        VISCOSITY_WATER,
        VISCOSITY_GAS,
        INJECTED_GAS_FORMATION_VOLUME_FACTOR,
        INJECTED_WATER_FORMATION_VOLUME_FACTOR,
        completion,
        vrr_date
    FROM ExactMatch

    UNION ALL

    -- Interpolation (lower and upper bounds exist)
    SELECT
        e.INPUT_PRESSURE AS PRESSURE,
        RMDE_SAM_ACC.Interpolate(
            l.PRESSURE,
            u.PRESSURE,
            l.OIL_FORMATION_VOLUME_FACTOR,
            u.OIL_FORMATION_VOLUME_FACTOR,
            e.INPUT_PRESSURE
        ) AS OIL_FORMATION_VOLUME_FACTOR,
        RMDE_SAM_ACC.Interpolate(
            l.PRESSURE,
            u.PRESSURE,
            l.GAS_FORMATION_VOLUME_FACTOR,
            u.GAS_FORMATION_VOLUME_FACTOR,
            e.INPUT_PRESSURE
        ) AS GAS_FORMATION_VOLUME_FACTOR,
        RMDE_SAM_ACC.Interpolate(
            l.PRESSURE,
            u.PRESSURE,
            l.WATER_FORMATION_VOLUME_FACTOR,
            u.WATER_FORMATION_VOLUME_FACTOR,
            e.INPUT_PRESSURE
        ) AS WATER_FORMATION_VOLUME_FACTOR,
        RMDE_SAM_ACC.Interpolate(
            l.PRESSURE,
            u.PRESSURE,
            l.SOLUTION_GAS_OIL_RATIO,
            u.SOLUTION_GAS_OIL_RATIO,
            e.INPUT_PRESSURE
        ) AS SOLUTION_GAS_OIL_RATIO,
        RMDE_SAM_ACC.Interpolate(
            l.PRESSURE,
            u.PRESSURE,
            l.VOLATIZED_OIL_GAS_RATIO,
            u.VOLATIZED_OIL_GAS_RATIO,
            e.INPUT_PRESSURE
        ) AS VOLATIZED_OIL_GAS_RATIO,
        RMDE_SAM_ACC.Interpolate(
            l.PRESSURE,
            u.PRESSURE,
            l.VISCOSITY_OIL,
            u.VISCOSITY_OIL,
            e.INPUT_PRESSURE
        ) AS VISCOSITY_OIL,
        RMDE_SAM_ACC.Interpolate(
            l.PRESSURE,
            u.PRESSURE,
            l.VISCOSITY_WATER,
            u.VISCOSITY_WATER,
            e.INPUT_PRESSURE
        ) AS VISCOSITY_WATER,
        RMDE_SAM_ACC.Interpolate(
            l.PRESSURE,
            u.PRESSURE,
            l.VISCOSITY_GAS,
            u.VISCOSITY_GAS,
            e.INPUT_PRESSURE
        ) AS VISCOSITY_GAS,
        RMDE_SAM_ACC.Interpolate(
            l.PRESSURE,
            u.PRESSURE,
            l.INJECTED_GAS_FORMATION_VOLUME_FACTOR,
            u.INJECTED_GAS_FORMATION_VOLUME_FACTOR,
            e.INPUT_PRESSURE
        ) AS INJECTED_GAS_FORMATION_VOLUME_FACTOR,
        RMDE_SAM_ACC.Interpolate(
            l.PRESSURE,
            u.PRESSURE,
            l.INJECTED_WATER_FORMATION_VOLUME_FACTOR,
            u.INJECTED_WATER_FORMATION_VOLUME_FACTOR,
            e.INPUT_PRESSURE
        ) AS INJECTED_WATER_FORMATION_VOLUME_FACTOR,
        e.INPUT_COMPLETION AS completion,
        e.INPUT_VRR_DATE AS vrr_date
    FROM PVTwithEndDate e
    JOIN LowerBound l ON l.completion = e.INPUT_COMPLETION AND l.vrr_date = e.INPUT_VRR_DATE
    JOIN UpperBound u ON u.completion = e.INPUT_COMPLETION AND u.vrr_date = e.INPUT_VRR_DATE
    WHERE NOT EXISTS (SELECT 1 FROM ExactMatch em WHERE em.completion = e.INPUT_COMPLETION AND em.vrr_date = e.INPUT_VRR_DATE)

    UNION ALL

    -- Extrapolation (upper bound and second bound exist, no lower bound or exact match)
    SELECT
        e.INPUT_PRESSURE AS PRESSURE,
        RMDE_SAM_ACC.Extrapolate(
            u.PRESSURE,
            s.PRESSURE,
            u.OIL_FORMATION_VOLUME_FACTOR,
            s.OIL_FORMATION_VOLUME_FACTOR,
            e.INPUT_PRESSURE
        ) AS OIL_FORMATION_VOLUME_FACTOR,
        RMDE_SAM_ACC.Extrapolate(
            u.PRESSURE,
            s.PRESSURE,
            u.GAS_FORMATION_VOLUME_FACTOR,
            s.GAS_FORMATION_VOLUME_FACTOR,
            e.INPUT_PRESSURE
        ) AS GAS_FORMATION_VOLUME_FACTOR,
        RMDE_SAM_ACC.Extrapolate(
            u.PRESSURE,
            s.PRESSURE,
            u.WATER_FORMATION_VOLUME_FACTOR,
            s.WATER_FORMATION_VOLUME_FACTOR,
            e.INPUT_PRESSURE
        ) AS WATER_FORMATION_VOLUME_FACTOR,
        RMDE_SAM_ACC.Extrapolate(
            u.PRESSURE,
            s.PRESSURE,
            u.SOLUTION_GAS_OIL_RATIO,
            s.SOLUTION_GAS_OIL_RATIO,
            e.INPUT_PRESSURE
        ) AS SOLUTION_GAS_OIL_RATIO,
        RMDE_SAM_ACC.Extrapolate(
            u.PRESSURE,
            s.PRESSURE,
            u.VOLATIZED_OIL_GAS_RATIO,
            s.VOLATIZED_OIL_GAS_RATIO,
            e.INPUT_PRESSURE
        ) AS VOLATIZED_OIL_GAS_RATIO,
        RMDE_SAM_ACC.Extrapolate(
            u.PRESSURE,
            s.PRESSURE,
            u.VISCOSITY_OIL,
            s.VISCOSITY_OIL,
            e.INPUT_PRESSURE
        ) AS VISCOSITY_OIL,
        RMDE_SAM_ACC.Extrapolate(
            u.PRESSURE,
            s.PRESSURE,
            u.VISCOSITY_WATER,
            s.VISCOSITY_WATER,
            e.INPUT_PRESSURE
        ) AS VISCOSITY_WATER,
        RMDE_SAM_ACC.Extrapolate(
            u.PRESSURE,
            s.PRESSURE,
            u.VISCOSITY_GAS,
            s.VISCOSITY_GAS,
            e.INPUT_PRESSURE
        ) AS VISCOSITY_GAS,
        RMDE_SAM_ACC.Extrapolate(
            u.PRESSURE,
            s.PRESSURE,
            u.INJECTED_GAS_FORMATION_VOLUME_FACTOR,
            s.INJECTED_GAS_FORMATION_VOLUME_FACTOR,
            e.INPUT_PRESSURE
        ) AS INJECTED_GAS_FORMATION_VOLUME_FACTOR,
        RMDE_SAM_ACC.Extrapolate(
            u.PRESSURE,
            s.PRESSURE,
            u.INJECTED_WATER_FORMATION_VOLUME_FACTOR,
            s.INJECTED_WATER_FORMATION_VOLUME_FACTOR,
            e.INPUT_PRESSURE
        ) AS INJECTED_WATER_FORMATION_VOLUME_FACTOR,
        e.INPUT_COMPLETION AS completion,
        e.INPUT_VRR_DATE AS vrr_date
    FROM PVTwithEndDate e
    JOIN UpperBound u ON u.completion = e.INPUT_COMPLETION AND u.vrr_date = e.INPUT_VRR_DATE
    JOIN SecondBound s ON s.completion = e.INPUT_COMPLETION AND s.vrr_date = e.INPUT_VRR_DATE
    WHERE NOT EXISTS (SELECT 1 FROM LowerBound l WHERE l.completion = e.INPUT_COMPLETION AND l.vrr_date = e.INPUT_VRR_DATE)
      AND NOT EXISTS (SELECT 1 FROM ExactMatch em WHERE em.completion = e.INPUT_COMPLETION AND em.vrr_date = e.INPUT_VRR_DATE)
      AND (SELECT COUNT(*) FROM PVTwithEndDate p WHERE p.ID_COMPLETION = e.INPUT_COMPLETION AND p.PRESSURE > e.INPUT_PRESSURE AND p.TEST_DATE <= LAST_DAY(e.INPUT_VRR_DATE)) > 1

    UNION ALL

    -- No valid data
    SELECT
        INPUT_PRESSURE AS PRESSURE,
        NULL AS OIL_FORMATION_VOLUME_FACTOR,
        NULL AS GAS_FORMATION_VOLUME_FACTOR,
        NULL AS WATER_FORMATION_VOLUME_FACTOR,
        NULL AS SOLUTION_GAS_OIL_RATIO,
        NULL AS VOLATIZED_OIL_GAS_RATIO,
        NULL AS VISCOSITY_OIL,
        NULL AS VISCOSITY_WATER,
        NULL AS VISCOSITY_GAS,
        NULL AS INJECTED_GAS_FORMATION_VOLUME_FACTOR,
        NULL AS INJECTED_WATER_FORMATION_VOLUME_FACTOR,
        INPUT_COMPLETION AS completion,
        INPUT_VRR_DATE AS vrr_date
    FROM PVTwithEndDate e
    WHERE NOT EXISTS (SELECT 1 FROM ExactMatch em WHERE em.completion = e.INPUT_COMPLETION AND em.vrr_date = e.INPUT_VRR_DATE)
      AND NOT EXISTS (SELECT 1 FROM LowerBound l WHERE l.completion = e.INPUT_COMPLETION AND l.vrr_date = e.INPUT_VRR_DATE)
      AND NOT EXISTS (SELECT 1 FROM UpperBound u WHERE u.completion = e.INPUT_COMPLETION AND u.vrr_date = e.INPUT_VRR_DATE)
)
SELECT
    ROUND(PRESSURE, 5) AS PRESSURE,
    ROUND(OIL_FORMATION_VOLUME_FACTOR, 5) AS OIL_FORMATION_VOLUME_FACTOR,
    ROUND(GAS_FORMATION_VOLUME_FACTOR, 5) AS GAS_FORMATION_VOLUME_FACTOR,
    ROUND(WATER_FORMATION_VOLUME_FACTOR, 5) AS WATER_FORMATION_VOLUME_FACTOR,
    ROUND(SOLUTION_GAS_OIL_RATIO, 5) AS SOLUTION_GAS_OIL_RATIO,
    ROUND(VOLATIZED_OIL_GAS_RATIO, 5) AS VOLATIZED_OIL_GAS_RATIO,
    ROUND(VISCOSITY_OIL, 5) AS VISCOSITY_OIL,
    ROUND(VISCOSITY_WATER, 5) AS VISCOSITY_WATER,
    ROUND(VISCOSITY_GAS, 5) AS VISCOSITY_GAS,
    ROUND(INJECTED_GAS_FORMATION_VOLUME_FACTOR, 5) AS INJECTED_GAS_FORMATION_VOLUME_FACTOR,
    ROUND(INJECTED_WATER_FORMATION_VOLUME_FACTOR, 5) AS INJECTED_WATER_FORMATION_VOLUME_FACTOR,
    completion AS ID_COMPLETION,
    vrr_date AS VRR_DATE
FROM InterpolatedValues
QUALIFY ROW_NUMBER() OVER (PARTITION BY completion, vrr_date, PRESSURE ORDER BY PRESSURE) = 1;

-- Create view for PATTERN_VRR_VIEW with Snowflake mappings
CREATE OR REPLACE VIEW RMDE_SAM_ACC.PATTERN_VRR_VIEW
AS
SELECT *
FROM (
    SELECT
        CONCAT(ID_PATTERN, TO_CHAR(DATE, 'DD-MM-YYYY')) AS ID_PATTERN_VRR,
        ID_PATTERN,
        DATE,
        PRESSURE,
        COALESCE((INJECTION_VOLUME_RES_BBL / NULLIF(PRODUCTION_VOLUME_RES_BBL, 0)), 0) AS VRR,
        COALESCE((CUMULATIVE_INJECTION_VOLUME_RES_BBL / NULLIF(CUMULATIVE_PRODUCTION_VOLUME_RES_BBL, 0)), 0) AS CUMULATIVE_VRR,
        OIL_VOLUME_STB,
        OIL_VOLUME_RES_BBL,
        GAS_VOLUME_SCF,
        FREE_GAS,
        WATER_VOLUME_STB,
        WATER_VOLUME_RES_BBL,
        PRODUCTION_VOLUME_RES_BBL,
        CUMULATIVE_PRODUCTION_VOLUME_RES_BBL,
        GAS_INJ_VOLUME_SCF,
        WATER_INJ_VOLUME_STB,
        INJECTION_VOLUME_RES_BBL,
        CUMULATIVE_INJECTION_VOLUME_RES_BBL,
        WATER_INJ_VOLUME_RES_BBL,
        GAS_INJ_VOLUME_RES_BBL,
        CUMULATIVE_OIL_PRODUCTION_VOLUME_RES_BBL,
        CUMULATIVE_WATER_PRODUCTION_VOLUME_RES_BBL,
        CUMULATIVE_WATER_INJECTION_VOLUME_RES_BBL,
        CUMULATIVE_GAS_INJECTION_VOLUME_RES_BBL
    FROM (
        SELECT
            ID_PATTERN,
            DATE,
            SUM(OIL_VOLUME) AS OIL_VOLUME_STB,
            SUM(WATER_VOLUME) AS WATER_VOLUME_STB,
            SUM(OIL_VOLUME * OIL_FORMATION_VOLUME_FACTOR) AS OIL_VOLUME_RES_BBL,
            SUM(WATER_VOLUME * WATER_FORMATION_VOLUME_FACTOR) AS WATER_VOLUME_RES_BBL,
            SUM(WATER_INJ_VOLUME) AS WATER_INJ_VOLUME_STB,
            SUM(WATER_INJ_VOLUME * INJECTED_WATER_FORMATION_VOLUME_FACTOR) AS WATER_INJ_VOLUME_RES_BBL,
            SUM(GAS_WELL_GAS_VOLUME) AS GAS_WELL_GAS_VOLUME_SCF,
            SUM(GAS_INJ_VOLUME) AS GAS_INJ_VOLUME_SCF,
            SUM(GAS_VOLUME) AS GAS_VOLUME_SCF,
            SUM(FREE_GAS) AS FREE_GAS,
            SUM(SUM(OIL_VOLUME * OIL_FORMATION_VOLUME_FACTOR)) OVER (PARTITION BY ID_PATTERN ORDER BY DATE ASC) AS CUMULATIVE_OIL_PRODUCTION_VOLUME_RES_BBL,
            SUM(SUM(WATER_VOLUME * WATER_FORMATION_VOLUME_FACTOR)) OVER (PARTITION BY ID_PATTERN ORDER BY DATE ASC) AS CUMULATIVE_WATER_PRODUCTION_VOLUME_RES_BBL,
            SUM(SUM(WATER_INJ_VOLUME * INJECTED_WATER_FORMATION_VOLUME_FACTOR)) OVER (PARTITION BY ID_PATTERN ORDER BY DATE ASC) AS CUMULATIVE_WATER_INJECTION_VOLUME_RES_BBL,
            SUM(SUM(GAS_INJ_VOLUME * INJECTED_GAS_FORMATION_VOLUME_FACTOR)) OVER (PARTITION BY ID_PATTERN ORDER BY DATE ASC) AS CUMULATIVE_GAS_INJECTION_VOLUME_RES_BBL,
            SUM(GAS_INJ_VOLUME * INJECTED_GAS_FORMATION_VOLUME_FACTOR) AS GAS_INJ_VOLUME_RES_BBL,
            SUM(OIL_VOLUME * OIL_FORMATION_VOLUME_FACTOR) + SUM(WATER_VOLUME * WATER_FORMATION_VOLUME_FACTOR) + SUM(FREE_GAS) AS PRODUCTION_VOLUME_RES_BBL,
            SUM(SUM(OIL_VOLUME * OIL_FORMATION_VOLUME_FACTOR) + SUM(WATER_VOLUME * WATER_FORMATION_VOLUME_FACTOR)) OVER (PARTITION BY ID_PATTERN ORDER BY DATE ASC) AS CUMULATIVE_PRODUCTION_VOLUME_RES_BBL,
            SUM(SUM(WATER_INJ_VOLUME * INJECTED_WATER_FORMATION_VOLUME_FACTOR) + SUM(GAS_INJ_VOLUME * INJECTED_GAS_FORMATION_VOLUME_FACTOR)) AS INJECTION_VOLUME_RES_BBL,
            SUM(SUM(WATER_INJ_VOLUME * INJECTED_WATER_FORMATION_VOLUME_FACTOR) + SUM(GAS_INJ_VOLUME * INJECTED_GAS_FORMATION_VOLUME_FACTOR)) OVER (PARTITION BY ID_PATTERN ORDER BY DATE ASC) AS CUMULATIVE_INJECTION_VOLUME_RES_BBL,
            SUM(SOLUTION_GAS_OIL_RATIO) AS SOLUTION_GAS_OIL_RATIO,
            AVG(PRESSURE) AS PRESSURE
        FROM (
            SELECT
                daily_volume.ID_PATTERN,
                daily_volume.COMPLETION_ID AS ID_COMPLETION,
                daily_volume.PROD_DATE AS DATE,
                COALESCE(daily_volume.THEOR_OIL_VOL_STB * split_factors.FACTOR, daily_volume.THEOR_OIL_VOL_STB, 0) AS OIL_VOLUME,
                COALESCE(daily_volume.THEOR_WATER_VOL_STB * split_factors.FACTOR, daily_volume.THEOR_WATER_VOL_STB, 0) AS WATER_VOLUME,
                COALESCE(daily_volume.THEOR_GAS_VOL_KSCF * 1000 * split_factors.FACTOR, daily_volume.THEOR_GAS_VOL_KSCF * 1000, 0) AS GAS_VOLUME,
                COALESCE(daily_volume.THEOR_WATER_INJ_VOL_STB * split_factors.FACTOR, daily_volume.THEOR_WATER_INJ_VOL_STB, 0) AS WATER_INJ_VOLUME,
                COALESCE(daily_volume.ALLOC_GAS_VOL_KSCF * 1000 * split_factors.FACTOR, daily_volume.ALLOC_GAS_VOL_KSCF * 1000, 0) AS GAS_WELL_GAS_VOLUME,
                COALESCE(daily_volume.THEOR_GAS_INJ_VOL_KSCF * 1000 * split_factors.FACTOR, daily_volume.THEOR_GAS_INJ_VOL_KSCF * 1000, 0) AS GAS_INJ_VOLUME,
                CASE
                    WHEN Amount_Type = 'Production' THEN COALESCE(FREE_GAS * split_factors.FACTOR * pvt.GAS_FORMATION_VOLUME_FACTOR, FREE_GAS, 0)
                    ELSE 0
                END AS FREE_GAS,
                split_factors.FACTOR,
                add_pressures.PRESSURE,
                pvt.OIL_FORMATION_VOLUME_FACTOR,
                pvt.GAS_FORMATION_VOLUME_FACTOR,
                pvt.WATER_FORMATION_VOLUME_FACTOR,
                pvt.SOLUTION_GAS_OIL_RATIO,
                pvt.VOLATIZED_OIL_GAS_RATIO,
                pvt.VISCOSITY_OIL,
                pvt.VISCOSITY_WATER,
                pvt.VISCOSITY_GAS,
                pvt.INJECTED_GAS_FORMATION_VOLUME_FACTOR,
                pvt.INJECTED_WATER_FORMATION_VOLUME_FACTOR,
                Amount_Type
            FROM TRUSTED_DB.PRODUCTION_VOLUME.PRODUCTION_VOLUMES_DAILY_OILFIELD daily_volume
            LEFT JOIN RMDE_SAM_ACC.PATTERN_CONTRIBUTION_FACTOR split_factors
                ON daily_volume.COMPLETION_ID = split_factors.ID_COMPLETION
                AND split_factors.EFFECT_DATE = (
                    SELECT MAX(EFFECT_DATE)
                    FROM RMDE_SAM_ACC.PATTERN_CONTRIBUTION_FACTOR
                    WHERE ID_PATTERN = split_factors.ID_PATTERN
                      AND ID_COMPLETION = daily_volume.COMPLETION_ID
                      AND daily_volume.PROD_DATE >= EFFECT_DATE
                )
            INNER JOIN (
                SELECT
                    ID_PATTERN,
                    DATE,
                    PRESSURE,
                    COALESCE(
                        LEAD(DATE, 1) OVER (PARTITION BY ID_PATTERN ORDER BY DATE),
                        '9999-12-31'::DATE
                    ) AS END_DATE
                FROM RMDE_SAM_ACC.PATTERN_PRESSURE
            ) add_pressures
                ON add_pressures.ID_PATTERN = split_factors.ID_PATTERN
                AND daily_volume.PROD_DATE >= add_pressures.DATE
                AND daily_volume.PROD_DATE < add_pressures.END_DATE
            LEFT JOIN RMDE_SAM_ACC.INTERPOLATE_PVT_COMPLETION_TEST_VIEW pvt
                ON pvt.ID_COMPLETION = daily_volume.COMPLETION_ID
                AND pvt.VRR_DATE = add_pressures.DATE
                AND pvt.PRESSURE = add_pressures.PRESSURE
            WHERE daily_volume.THEOR_GAS_VOL_KSCF IS NOT NULL
        ) splits
        GROUP BY ID_PATTERN, DATE, PRESSURE
    ) final
) nonzeroes
WHERE CUMULATIVE_PRODUCTION_VOLUME_RES_BBL != 0;
