-- VRR CALCULATIONS (OILFIELD STANDARD) --
CREATE OR REPLACE VIEW vr.PATTERN_VRR_VIEW
AS
WITH 
-- CTE 1: Calculate the end date (DATUM) for pressure data
Pressure_End_Dates AS (
    SELECT
        ID_PATTERN,
        DATE,
        COALESCE(
            LEAD(DATE, 1) OVER (PARTITION BY ID_PATTERN ORDER BY DATE),
            TO_TIMESTAMP('9999-12-31 00:00:00')
        ) AS DATUM
    FROM RMDE.SAM_ACC.PATTERN_PRESSURE
),

-- CTE 2: Join daily_volume with pressure end dates to filter valid completions
Filtered_Daily_Volume AS (
    SELECT 
        dv.ID_PATTERN,
        dv.COMPLETION_ID,
        dv.PROD_DATE AS DATE,
        dv.THEOR_OIL_VOL_STB,
        dv.THEOR_WATER_VOL_STB,
        dv.THEOR_GAS_VOL_KSCF,
        dv.CUMULATIVE_INJECTION_VOLUME_res_bbl,
        dv.CUMULATIVE_PRODUCTION_VOLUME_res_bbl,
        ap.PRESSURE AS PRESSURE_DATE
    FROM TRUSTED_DB.PRODUCTION_VOLUMES.DAILY_OILFIELD dv
    JOIN Pressure_End_Dates ped
        ON dv.ID_PATTERN = ped.ID_PATTERN
    JOIN RMDE.SAM_ACC.PATTERN_PRESSURE ap 
        ON dv.ID_PATTERN = ap.ID_PATTERN
        AND dv.PROD_DATE >= ap.DATE
        AND dv.PROD_DATE < ped.DATUM
),

-- CTE 3: Match split factors with the most recent effective date
Split_Factors_Matched AS (
    SELECT 
        sf.*,
        fdv.ID_PATTERN,
        fdv.DATE AS EFFECT_DATE
    FROM RMDE.SAM_ACC.PATTERN_CONTRIBUTION_FACTOR sf
    JOIN Filtered_Daily_Volume fdv
        ON sf.ID_PATTERN = fdv.ID_PATTERN
        AND fdv.DATE <= (
            SELECT MAX(EFFECT_DATE)
            FROM RMDE.SAM_ACC.PATTERN_CONTRIBUTION_FACTOR pcf
            WHERE pcf.ID_PATTERN = sf.ID_PATTERN
            AND fdv.DATE <= pcf.EFFECT_DATE
        )
),

-- CTE 4: Aggregate the data
Aggregated_Data AS (
    SELECT
        sfm.ID_PATTERN,
        sfm.EFFECT_DATE AS DATE,
        fdv.PRESSURE_DATE AS PRESSURE,
        COALESCE(fdv.THEOR_OIL_VOL_STB, 0) AS THEOR_OIL_VOL_STB,
        COALESCE(fdv.THEOR_WATER_VOL_STB, 0) AS THEOR_WATER_VOL_STB,
        COALESCE(fdv.THEOR_GAS_VOL_KSCF * 1000, 0) AS THEOR_GAS_VOL_KSCF,  -- kscf to scf
        sfm.*,
        fdv.CUMULATIVE_INJECTION_VOLUME_res_bbl,
        fdv.CUMULATIVE_PRODUCTION_VOLUME_res_bbl
    FROM Split_Factors_Matched sfm
    JOIN Filtered_Daily_Volume fdv
        ON sfm.ID_PATTERN = fdv.ID_PATTERN
        AND sfm.EFFECT_DATE = fdv.DATE
)

-- Final SELECT statement
SELECT
    CONCAT(agg.ID_PATTERN, TO_CHAR(agg.DATE, 'DD-MON-YYYY')) AS ID_PATTERN,
    agg.DATE,
    agg.PRESSURE,
    COALESCE(agg.CUMULATIVE_INJECTION_VOLUME_res_bbl / NULLIF(agg.CUMULATIVE_PRODUCTION_VOLUME_res_bbl, 0), 0) AS VRR_Injection_Volume_Production_Volume,
    -- OIL VOLUME (stb)
    agg.THEOR_OIL_VOL_STB,
    -- FREE GAS
    agg.THEOR_WATER_VOL_STB,
    agg.CUMULATIVE_PRODUCTION_VOLUME_res_bbl AS PRODUCTION_VOLUME_res_bbl,
    agg.GAS_FORMATION_VOLUME_FACTOR,
    agg.WATER_FORMATION_VOLUME_FACTOR,
    agg.THEOR_WATER_INJ_VOL_STB AS GAS_INJ_VOLUME_stb,  -- Adjusted to use THEOR_WATER_INJ_VOL_STB as per mapping
    agg.THEOR_WATER_INJ_VOL_STB AS WATER_INJ_VOLUME_stb,
    agg.INJECTED_WATER_FORMATION_VOLUME_FACTOR AS WATER_INJ_VOLUME,
    agg.INJECTED_GAS_FORMATION_VOLUME_FACTOR AS GAS_WELL_GAS_VOLUME,
    agg.THEOR_GAS_VOL_KSCF,
    -- FACTORS
    agg.PRESSURE AS PRESSURE_FACTOR,
    agg.GAS_FORMATION_VOLUME_FACTOR AS GAS_FORMATION_FACTOR,
    agg.WATER_FORMATION_VOLUME_FACTOR AS WATER_FORMATION_FACTOR,
    agg.SOLUTION_GAS_OIL_RATIO,
    agg.VOLATILIZED_OIL_GAS_RATIO,
    agg.VISCOSITY_OIL,
    agg.VISCOSITY_GAS,
    agg.VISCOSITY_WATER,
    agg.INJECTED_GAS_FORMATION_VOLUME_FACTOR AS INJECTED_GAS_FACTOR,
    agg.INJECTED_WATER_FORMATION_VOLUME_FACTOR AS INJECTED_WATER_FACTOR,
    agg.FACTOR AS FACTORS
FROM Aggregated_Data agg
WHERE agg.CUMULATIVE_PRODUCTION_VOLUME_res_bbl > 0
GROUP BY 
    agg.ID_PATTERN, 
    agg.DATE, 
    agg.PRESSURE,
    agg.CUMULATIVE_INJECTION_VOLUME_res_bbl,
    agg.CUMULATIVE_PRODUCTION_VOLUME_res_bbl,
    agg.THEOR_OIL_VOL_STB,
    agg.THEOR_WATER_VOL_STB,
    agg.THEOR_GAS_VOL_KSCF,
    agg.GAS_FORMATION_VOLUME_FACTOR,
    agg.WATER_FORMATION_VOLUME_FACTOR,
    agg.THEOR_WATER_INJ_VOL_STB,
    agg.INJECTED_WATER_FORMATION_VOLUME_FACTOR,
    agg.INJECTED_GAS_FORMATION_VOLUME_FACTOR,
    agg.SOLUTION_GAS_OIL_RATIO,
    agg.VOLATILIZED_OIL_GAS_RATIO,
    agg.VISCOSITY_OIL,
    agg.VISCOSITY_GAS,
    agg.VISCOSITY_WATER,
    agg.FACTOR;
