CREATE OR REPLACE VIEW RMDE_SAM_ACC.PATTERN_VRR_VIEW
AS
WITH Splits AS (
    SELECT
        dv.ID_PATTERN,
        dv.ID_COMPLETION,
        dv.Operating_Date AS DATE,
        -- Apply contribution factor to volumes
        COALESCE(dv.OIL_VOLUME * sf.FACTOR, dv.OIL_VOLUME, 0) AS OIL_VOLUME,
        COALESCE(dv.WATER_VOLUME * sf.FACTOR, dv.WATER_VOLUME, 0) AS WATER_VOLUME,
        COALESCE(dv.GAS_VOLUME * sf.FACTOR, dv.GAS_VOLUME, 0) AS GAS_VOLUME,
        COALESCE(dv.WATER_INJ_VOLUME * sf.FACTOR, dv.WATER_INJ_VOLUME, 0) AS WATER_INJ_VOLUME,
        COALESCE(dv.GAS_WELL_GAS_VOLUME * sf.FACTOR, dv.GAS_WELL_GAS_VOLUME, 0) AS GAS_WELL_GAS_VOLUME,
        COALESCE(dv.GAS_INJ_VOLUME * sf.FACTOR, dv.GAS_INJ_VOLUME, 0) AS GAS_INJ_VOLUME,
        CASE
            WHEN dv.Amount_Type = 'Production' THEN COALESCE(dv.FREE_GAS * sf.FACTOR * pvt.GAS_FORMATION_VOLUME_FACTOR, dv.FREE_GAS, 0)
            ELSE 0
        END AS FREE_GAS,
        sf.FACTOR,
        pp.PRESSURE,
        pvt.OIL_FORMATION_VOLUME_FACTOR,
        pvt.GAS_FORMATION_VOLUME_FACTOR,
        pvt.WATER_FORMATION_VOLUME_FACTOR,
        pvt.SOLUTION_GAS_OIL_RATIO,
        pvt.VOLATIZED_OIL_GAS_RATIO,
        pvt.VISCOSITY_OIL,
        pvt.VISCOSITY_WATER,
        pvt.VISCOSITY_GAS,
        pvt.INJECTED_GAS_FORMATION_VOLUME_FACTOR,
        pvt.INJECTED_WATER_FORMATION_VOLUME_FACTOR,
        dv.Amount_Type
    FROM RMDE_SAM_ACC.DAILY_VOLUME dv
    -- Match contribution factor
    LEFT JOIN RMDE_SAM_ACC.PATTERN_CONTRIBUTION_FACTOR sf
        ON dv.ID_COMPLETION = sf.ID_COMPLETION
        AND sf.EFFECT_DATE = (
            SELECT MAX(EFFECT_DATE)
            FROM RMDE_SAM_ACC.PATTERN_CONTRIBUTION_FACTOR sf2
            WHERE sf2.ID_PATTERN = sf.ID_PATTERN
              AND sf2.ID_PATTERN IN (
                  SELECT ID_PATTERN
                  FROM RMDE_SAM_ACC.PATTERN_CONTRIBUTION_FACTOR
                  WHERE ID_COMPLETION = dv.ID_COMPLETION
              )
              AND dv.Operating_Date >= sf2.EFFECT_DATE
        )
    -- Match pressure
    INNER JOIN (
        SELECT
            ID_PATTERN,
            DATE,
            PRESSURE,
            COALESCE(
                LEAD(DATE, 1) OVER (PARTITION BY ID_PATTERN ORDER BY DATE),
                '9999-12-31'::DATE
            ) AS END_DATE
        FROM RMDE_SAM_ACC.PATTERN_PRESSURE
    ) pp
        ON pp.ID_PATTERN = sf.ID_PATTERN
        AND dv.Operating_Date >= pp.DATE
        AND dv.Operating_Date < pp.END_DATE
    -- Match PVT characteristics
    LATERAL RMDE_SAM_ACC.InterpolatePVTCompletionTest(pp.PRESSURE, dv.ID_COMPLETION, pp.DATE) pvt
),
Final AS (
    SELECT
        ID_PATTERN,
        DATE,
        AVG(PRESSURE) AS PRESSURE,
        SUM(SOLUTION_GAS_OIL_RATIO) AS SOLUTION_GAS_OIL_RATIO,
        SUM(OIL_VOLUME) AS OIL_VOLUME_STB,
        SUM(WATER_VOLUME) AS WATER_VOLUME_STB,
        SUM(OIL_VOLUME * OIL_FORMATION_VOLUME_FACTOR) AS OIL_VOLUME_RES_BBL,
        SUM(WATER_VOLUME * WATER_FORMATION_VOLUME_FACTOR) AS WATER_VOLUME_RES_BBL,
        SUM(WATER_INJ_VOLUME) AS WATER_INJ_VOLUME_STB,
        SUM(WATER_INJ_VOLUME * INJECTED_WATER_FORMATION_VOLUME_FACTOR) AS WATER_INJ_VOLUME_RES_BBL,
        SUM(GAS_WELL_GAS_VOLUME) AS GAS_WELL_GAS_VOLUME_SCF,
        SUM(GAS_INJ_VOLUME) AS GAS_INJ_VOLUME_SCF,
        SUM(GAS_VOLUME) AS GAS_VOLUME_SCF,
        SUM(FREE_GAS) AS FREE_GAS,
        SUM(SUM(OIL_VOLUME * OIL_FORMATION_VOLUME_FACTOR)) OVER (PARTITION BY ID_PATTERN ORDER BY DATE) AS CUMULATIVE_OIL_PRODUCTION_VOLUME_RES_BBL,
        SUM(SUM(WATER_VOLUME * WATER_FORMATION_VOLUME_FACTOR)) OVER (PARTITION BY ID_PATTERN ORDER BY DATE) AS CUMULATIVE_WATER_PRODUCTION_VOLUME_RES_BBL,
        SUM(SUM(WATER_INJ_VOLUME * INJECTED_WATER_FORMATION_VOLUME_FACTOR)) OVER (PARTITION BY ID_PATTERN ORDER BY DATE) AS CUMULATIVE_WATER_INJECTION_VOLUME_RES_BBL,
        SUM(SUM(GAS_INJ_VOLUME * INJECTED_GAS_FORMATION_VOLUME_FACTOR)) OVER (PARTITION BY ID_PATTERN ORDER BY DATE) AS CUMULATIVE_GAS_INJECTION_VOLUME_RES_BBL,
        SUM(GAS_INJ_VOLUME * INJECTED_GAS_FORMATION_VOLUME_FACTOR) AS GAS_INJ_VOLUME_RES_BBL,
        SUM(OIL_VOLUME * OIL_FORMATION_VOLUME_FACTOR) + SUM(WATER_VOLUME * WATER_FORMATION_VOLUME_FACTOR) + SUM(FREE_GAS) AS PRODUCTION_VOLUME_RES_BBL,
        SUM(SUM(OIL_VOLUME * OIL_FORMATION_VOLUME_FACTOR) + SUM(WATER_VOLUME * WATER_FORMATION_VOLUME_FACTOR)) OVER (PARTITION BY ID_PATTERN ORDER BY DATE) AS CUMULATIVE_PRODUCTION_VOLUME_RES_BBL,
        SUM(WATER_INJ_VOLUME * INJECTED_WATER_FORMATION_VOLUME_FACTOR) + SUM(GAS_INJ_VOLUME * INJECTED_GAS_FORMATION_VOLUME_FACTOR) AS INJECTION_VOLUME_RES_BBL,
        SUM(SUM(WATER_INJ_VOLUME * INJECTED_WATER_FORMATION_VOLUME_FACTOR) + SUM(GAS_INJ_VOLUME * INJECTED_GAS_FORMATION_VOLUME_FACTOR)) OVER (PARTITION BY ID_PATTERN ORDER BY DATE) AS CUMULATIVE_INJECTION_VOLUME_RES_BBL
    FROM Splits
    GROUP BY ID_PATTERN, DATE, PRESSURE
),
NonZeroes AS (
    SELECT
        CONCAT(ID_PATTERN, TO_CHAR(DATE, 'DD-MM-YYYY')) AS ID_PATTERN_VRR,
        ID_PATTERN,
        DATE,
        PRESSURE,
        COALESCE(INJECTION_VOLUME_RES_BBL / NULLIF(PRODUCTION_VOLUME_RES_BBL, 0), 0) AS VRR,
        COALESCE(CUMULATIVE_INJECTION_VOLUME_RES_BBL / NULLIF(CUMULATIVE_PRODUCTION_VOLUME_RES_BBL, 0), 0) AS CUMULATIVE_VRR,
        OIL_VOLUME_STB AS OIL_VOLUME_STB,
        OIL_VOLUME_RES_BBL AS OIL_VOLUME_RES_BBL,
        GAS_VOLUME_SCF AS GAS_VOLUME_SCF,
        FREE_GAS,
        WATER_VOLUME_STB AS WATER_VOLUME_STB,
        WATER_VOLUME_RES_BBL AS WATER_VOLUME_RES_BBL,
        PRODUCTION_VOLUME_RES_BBL AS PRODUCTION_VOLUME_RES_BBL,
        CUMULATIVE_PRODUCTION_VOLUME_RES_BBL AS CUMULATIVE_PRODUCTION_VOLUME_RES_BBL,
        GAS_INJ_VOLUME_SCF AS GAS_INJ_VOLUME_SCF,
        WATER_INJ_VOLUME_STB AS WATER_INJ_VOLUME_STB,
        INJECTION_VOLUME_RES_BBL AS INJECTION_VOLUME_RES_BBL,
        CUMULATIVE_INJECTION_VOLUME_RES_BBL AS CUMULATIVE_INJECTION_VOLUME_RES_BBL,
        WATER_INJ_VOLUME_RES_BBL AS WATER_INJ_VOLUME_RES_BBL,
        GAS_INJ_VOLUME_RES_BBL AS GAS_INJ_VOLUME_RES_BBL,
        CUMULATIVE_OIL_PRODUCTION_VOLUME_RES_BBL AS CUMULATIVE_OIL_PRODUCTION_VOLUME_RES_BBL,
        CUMULATIVE_WATER_PRODUCTION_VOLUME_RES_BBL AS CUMULATIVE_WATER_PRODUCTION_VOLUME_RES_BBL,
        CUMULATIVE_WATER_INJECTION_VOLUME_RES_BBL AS CUMULATIVE_WATER_INJECTION_VOLUME_RES_BBL,
        CUMULATIVE_GAS_INJECTION_VOLUME_RES_BBL AS CUMULATIVE_GAS_INJECTION_VOLUME_RES_BBL
    FROM Final
)
SELECT *
FROM NonZeroes
WHERE CUMULATIVE_PRODUCTION_VOLUME_RES_BBL != 0;
